# Broadcasting

---
The process of adjusting the dimentions of 2 arrays with different Dimension during arithmetic operations.

# Three Rules

1. Adjusting the change in no of dimention
2. Adjusting the change in size
3. Error if above both does not work

# Rule - 1

 If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.


In [3]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
result = A + B
print(result)

[[11 22 33]
 [14 25 36]]


In [8]:
A = np.array([1, 2, 3])

B = np.array([[10,20, 30],
              [4, 5, 6],
              [4, 5, 6]])
result = A + B
print(result)


[[11 22 33]
 [ 5  7  9]
 [ 5  7  9]]


In [9]:
M = np.ones((2, 3))
a = np.arange(3)
result = M + a
print(result)


[[1. 2. 3.]
 [1. 2. 3.]]


In [26]:
C = np.array([[2],
              [3],
              [5]])

D = np.array([10, 20, 30])

result = C * D
print(result)

[[ 20  40  60]
 [ 30  60  90]
 [ 50 100 150]]


# Rule - 2

If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.


In [16]:
C = np.array([[2],
              [3],
              [4]])

D = np.array([[10, 20, 30],
             [10, 20, 30],
             [10, 20, 30]])

result = C * D
print(result)

[[ 20  40  60]
 [ 30  60  90]
 [ 40  80 120]]


In [12]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
result = a * b
print(result)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [18]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
result = A + B
print(result)

[[11 22 33]
 [14 25 36]]


# Rule - 3

If in any dimension the sizes disagree and neither is equal to 1, an error is raised.


In [19]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20])
result = A + B
print(result)

ValueError: ignored

In [21]:
C = np.array([[2, 3]])

D = np.array([10, 20, 30])
result = C + D
print(result)

ValueError: ignored

In [25]:
E = np.array([[1, 2],
              [3, 4]])

scalar = [5,3,5]
result = E * scalar
print(result)

ValueError: ignored